CREATE TABLE vocabulab_cards (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    Spa_content TEXT NOT NULL,
    Eng_content TEXT NOT NULL,
    date_created TIMESTAMP DEFAULT now() NOT NULL
);

CREATE TABLE vocabulab_notes (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    note TEXT,
    favorite BOOLEAN,
    known BOOLEAN,
    date_created TIMESTAMP DEFAULT now() NOT NULL,
    card_id INTEGER
        REFERENCES vocabulab_cards(id) ON DELETE CASCADE NOT NULL,
    user_id INTEGER
        REFERENCES vocabulab_cards(id) ON DELETE CASCADE NOT NULL
);