CREATE TYPE diff AS ENUM ('b','i','a');

CREATE TABLE vocabulab_cards (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    spa_content TEXT NOT NULL,
    eng_content TEXT NOT NULL,
    difficulty diff default 'b',
    date_created TIMESTAMP DEFAULT now() NOT NULL
);

CREATE TABLE vocabulab_users (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_name TEXT NOT NULL UNIQUE,
  full_name TEXT NOT NULL,
  password TEXT NOT NULL,
  nickname TEXT,
  date_created TIMESTAMP DEFAULT now() NOT NULL,
  date_modified TIMESTAMP
);

CREATE TABLE vocabulab_notes (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    note TEXT,
    cardData text,
    favorite BOOLEAN, -- default as false
    known BOOLEAN, -- set default value "something"
    date_created TIMESTAMP DEFAULT now() NOT NULL,
    card_id INTEGER
        REFERENCES vocabulab_cards(id) ON DELETE CASCADE NOT NULL,
    user_id INTEGER
        REFERENCES vocabulab_users(id) ON DELETE CASCADE NOT NULL
);

ALTER TABLE vocabulab_notes
  ADD COLUMN
    author_id INTEGER REFERENCES vocabulab_users(id)
    ON DELETE SET NULL;
